import type { Metadata } from "next";
import { Playfair_Display } from "next/font/google";
import "./globals.css";
// import { GsapProvider } from "./components/gsapContext";
// import gsap from "gsap";
// import {ScrambleTextPlugin} from "gsap/ScrambleTextPlugin";

const playfair = Playfair_Display({
  weight: ["400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // gsap.registerPlugin(ScrambleTextPlugin);

  return (
    <html lang="en">
      {/* <GsapProvider> */}
        <body className={playfair.className}>{children}</body>
      {/* </GsapProvider> */}
    </html>
  );
}
